version: '2'
services:
  chrome:
    image: selenium/node-chrome
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  firefox:
    image: selenium/node-firefox
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"

  edge:
    image: selenium/node-edge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6903:5900"

  selenium-hub:
    image: selenium/hub
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  dotnet-selenium-tests:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: . # Build from the current directory where the Dockerfile is located
      dockerfile: Dockerfile # Specify the Dockerfile name
    depends_on:
      - selenium-hub
    environment:
      SELENIUM_HUB_URL: http://selenium-hub:4444/wd/hub # The URL for your tests to connect to
    command: dotnet test