# This workflow will build a .NET project  
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net  

name: .NET  

on:  
 push:  
   branches: [ "dev" ]  
 pull_request:  
   branches: [ "dev" ]
 workflow_dispatch:


jobs:  
 set-up-containers:  
   runs-on: self-hosted  

   steps:  
   - uses: actions/checkout@v4  
  
   - name: Set up Docker Compose  
     uses: docker/setup-compose-action@v1  
     with:  
       version: latest  

   - name: Start containers  
     run: docker compose up -d  

 set-up-dotnet:
   runs-on: self-hosted

   needs: set-up-containers

   steps:
   - uses: actions/checkout@v4

   - name: Setup .NET  
     uses: actions/setup-dotnet@v4  
     with:  
       dotnet-version: 8.0.x  

 build-and-test-chrome:
   runs-on: [self-hosted, action-runner-1]

   env:
     TEST_BROWSER: chrome

   needs: set-up-dotnet

   steps:
   - uses: actions/checkout@v4
     
   - name: Restore dependencies  
     run: dotnet restore  

   - name: Build  
     run: dotnet build --no-restore  

   - name: Run tests on Chrome  
     run: dotnet test --no-build --verbosity normal  

 build-and-test-firefox:
   runs-on: [self-hosted, action-runner-2]

   env:
     TEST_BROWSER: firefox

   needs: set-up-dotnet

   steps:
   - uses: actions/checkout@v4
     
   - name: Restore dependencies  
     run: dotnet restore  

   - name: Build  
     run: dotnet build --no-restore  

   - name: Run tests on Firefox  
     run: dotnet test --no-build --verbosity normal  

 build-and-test-edge:
   runs-on: [self-hosted, action-runner-3]

   env:
     TEST_BROWSER: edge

   needs: set-up-dotnet

   steps:
   - uses: actions/checkout@v4
     
   - name: Restore dependencies  
     run: dotnet restore  

   - name: Build  
     run: dotnet build --no-restore  

   - name: Run tests on Edge  
     run: dotnet test --no-build --verbosity normal  

 stop-containers:
   runs-on: self-hosted

   needs: build-and-test

   steps:
   - uses: actions/checkout@v4

   - name: Stop containers  
     if: always()  
     run: docker compose down
