# This workflow will build a .NET project  
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net  

name: .NET  

on:  
 push:  
   branches: [ "fix/web-page-not-loading-in-time" ]  
 pull_request:  
   branches: [ "fix/web-page-not-loading-in-time" ]  

jobs:  
 build:  

   runs-on: ubuntu-latest  
   # container:  
   #   image: mcr.microsoft.com/dotnet/sdk:8.0  
   #   options: --user root  
   steps:  
   - uses: actions/checkout@v4  
   # - name: Set up Docker  
   #   uses: docker/setup-docker-action@v2  
   - name: Set up Docker Compose  
     uses: docker/setup-compose-action@v1  
     with:  
       version: latest  
   - name: Start containers  
     run: docker compose up -d
   - name: Wait for Selenium Grid to be ready
     run: |
       echo "Waiting for Selenium Grid to become ready..."
       for i in {1..20}; do
         echo "Attempt $i:"
         docker ps
         curl_output=$(curl -s http://localhost:4444/status || true)
         echo "Status endpoint response:"
         echo "$curl_output"
         if echo "$curl_output" | grep -q '"ready": true'; then
           echo "Selenium Grid is ready"
           break
         else
           echo "Selenium Grid not ready yet..."
           sleep 5
          fi
        done
   - name: Setup .NET  
     uses: actions/setup-dotnet@v4  
     with:  
       dotnet-version: 8.0.x  
   - name: Restore dependencies  
     run: dotnet restore  
   - name: Build  
     run: dotnet build --no-restore  
   - name: Test  
     run: dotnet test --no-build --verbosity normal  
   - name: Stop containers  
     if: always()  
     run: docker compose down
