# This workflow will build a .NET project  
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net  

name: .NET  

on:  
 push:  
   branches: [ "dev" ]  
 pull_request:  
   branches: [ "dev" ]  

jobs:  
 build:  
   runs-on: self-hosted  

   steps:  
   - uses: actions/checkout@v4  
  
   - name: Set up Docker Compose  
     uses: docker/setup-compose-action@v1  
     with:  
       version: latest  

   - name: Start containers  
     run: docker compose up -d  

   - name: Setup .NET  
     uses: actions/setup-dotnet@v4  
     with:  
       dotnet-version: 8.0.x  

   - name: Restore dependencies  
     run: dotnet restore  

   - name: Build  
     run: dotnet build --no-restore  

   - name: Test  
     run: dotnet test --no-build --verbosity normal  

   - name: Stop containers  
     if: always()  
     run: docker compose down
